/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleRegisterRouteImport } from './routes/simple-register'
import { Route as SimpleLoginRouteImport } from './routes/simple-login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as RawMaterialsIndexRouteImport } from './routes/raw-materials/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as StockVerificationRouteImport } from './routes/stock/verification'
import { Route as StockScanRouteImport } from './routes/stock/scan'
import { Route as StockLabelsRouteImport } from './routes/stock/labels'
import { Route as StockStockItemIdRouteImport } from './routes/stock/$stockItemId'
import { Route as RawMaterialsMaterialIdRouteImport } from './routes/raw-materials/$materialId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as AuthVerificationRouteImport } from './routes/auth/verification'
import { Route as AuthRegistrationRouteImport } from './routes/auth/registration'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as StockStocktakeIndexRouteImport } from './routes/stock/stocktake/index'
import { Route as StockStocktakeSessionIdRouteImport } from './routes/stock/stocktake/$sessionId'

const SimpleRegisterRoute = SimpleRegisterRouteImport.update({
  id: '/simple-register',
  path: '/simple-register',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleLoginRoute = SimpleLoginRouteImport.update({
  id: '/simple-login',
  path: '/simple-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsIndexRoute = RawMaterialsIndexRouteImport.update({
  id: '/raw-materials/',
  path: '/raw-materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockVerificationRoute = StockVerificationRouteImport.update({
  id: '/stock/verification',
  path: '/stock/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const StockScanRoute = StockScanRouteImport.update({
  id: '/stock/scan',
  path: '/stock/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StockLabelsRoute = StockLabelsRouteImport.update({
  id: '/stock/labels',
  path: '/stock/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const StockStockItemIdRoute = StockStockItemIdRouteImport.update({
  id: '/stock/$stockItemId',
  path: '/stock/$stockItemId',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsMaterialIdRoute = RawMaterialsMaterialIdRouteImport.update({
  id: '/raw-materials/$materialId',
  path: '/raw-materials/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/auth/verification',
  path: '/auth/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistrationRoute = AuthRegistrationRouteImport.update({
  id: '/auth/registration',
  path: '/auth/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const StockStocktakeIndexRoute = StockStocktakeIndexRouteImport.update({
  id: '/stock/stocktake/',
  path: '/stock/stocktake/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockStocktakeSessionIdRoute = StockStocktakeSessionIdRouteImport.update({
  id: '/stock/stocktake/$sessionId',
  path: '/stock/stocktake/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/simple-login': typeof SimpleLoginRoute
  '/simple-register': typeof SimpleRegisterRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/raw-materials/$materialId': typeof RawMaterialsMaterialIdRoute
  '/stock/$stockItemId': typeof StockStockItemIdRoute
  '/stock/labels': typeof StockLabelsRoute
  '/stock/scan': typeof StockScanRoute
  '/stock/verification': typeof StockVerificationRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/raw-materials/': typeof RawMaterialsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stock/stocktake/$sessionId': typeof StockStocktakeSessionIdRoute
  '/stock/stocktake/': typeof StockStocktakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/simple-login': typeof SimpleLoginRoute
  '/simple-register': typeof SimpleRegisterRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/raw-materials/$materialId': typeof RawMaterialsMaterialIdRoute
  '/stock/$stockItemId': typeof StockStockItemIdRoute
  '/stock/labels': typeof StockLabelsRoute
  '/stock/scan': typeof StockScanRoute
  '/stock/verification': typeof StockVerificationRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/raw-materials': typeof RawMaterialsIndexRoute
  '/stock': typeof StockIndexRoute
  '/stock/stocktake/$sessionId': typeof StockStocktakeSessionIdRoute
  '/stock/stocktake': typeof StockStocktakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/simple-login': typeof SimpleLoginRoute
  '/simple-register': typeof SimpleRegisterRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/raw-materials/$materialId': typeof RawMaterialsMaterialIdRoute
  '/stock/$stockItemId': typeof StockStockItemIdRoute
  '/stock/labels': typeof StockLabelsRoute
  '/stock/scan': typeof StockScanRoute
  '/stock/verification': typeof StockVerificationRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/raw-materials/': typeof RawMaterialsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/stock/stocktake/$sessionId': typeof StockStocktakeSessionIdRoute
  '/stock/stocktake/': typeof StockStocktakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/settings'
    | '/simple-login'
    | '/simple-register'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/verification'
    | '/orders/$orderId'
    | '/raw-materials/$materialId'
    | '/stock/$stockItemId'
    | '/stock/labels'
    | '/stock/scan'
    | '/stock/verification'
    | '/orders/'
    | '/products/'
    | '/raw-materials/'
    | '/stock/'
    | '/stock/stocktake/$sessionId'
    | '/stock/stocktake/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/settings'
    | '/simple-login'
    | '/simple-register'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/verification'
    | '/orders/$orderId'
    | '/raw-materials/$materialId'
    | '/stock/$stockItemId'
    | '/stock/labels'
    | '/stock/scan'
    | '/stock/verification'
    | '/orders'
    | '/products'
    | '/raw-materials'
    | '/stock'
    | '/stock/stocktake/$sessionId'
    | '/stock/stocktake'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/settings'
    | '/simple-login'
    | '/simple-register'
    | '/auth/error'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/registration'
    | '/auth/verification'
    | '/orders/$orderId'
    | '/raw-materials/$materialId'
    | '/stock/$stockItemId'
    | '/stock/labels'
    | '/stock/scan'
    | '/stock/verification'
    | '/orders/'
    | '/products/'
    | '/raw-materials/'
    | '/stock/'
    | '/stock/stocktake/$sessionId'
    | '/stock/stocktake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SettingsRoute: typeof SettingsRoute
  SimpleLoginRoute: typeof SimpleLoginRoute
  SimpleRegisterRoute: typeof SimpleRegisterRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RawMaterialsMaterialIdRoute: typeof RawMaterialsMaterialIdRoute
  StockStockItemIdRoute: typeof StockStockItemIdRoute
  StockLabelsRoute: typeof StockLabelsRoute
  StockScanRoute: typeof StockScanRoute
  StockVerificationRoute: typeof StockVerificationRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RawMaterialsIndexRoute: typeof RawMaterialsIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  StockStocktakeSessionIdRoute: typeof StockStocktakeSessionIdRoute
  StockStocktakeIndexRoute: typeof StockStocktakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple-register': {
      id: '/simple-register'
      path: '/simple-register'
      fullPath: '/simple-register'
      preLoaderRoute: typeof SimpleRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-login': {
      id: '/simple-login'
      path: '/simple-login'
      fullPath: '/simple-login'
      preLoaderRoute: typeof SimpleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials/': {
      id: '/raw-materials/'
      path: '/raw-materials'
      fullPath: '/raw-materials/'
      preLoaderRoute: typeof RawMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/verification': {
      id: '/stock/verification'
      path: '/stock/verification'
      fullPath: '/stock/verification'
      preLoaderRoute: typeof StockVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/scan': {
      id: '/stock/scan'
      path: '/stock/scan'
      fullPath: '/stock/scan'
      preLoaderRoute: typeof StockScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/labels': {
      id: '/stock/labels'
      path: '/stock/labels'
      fullPath: '/stock/labels'
      preLoaderRoute: typeof StockLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$stockItemId': {
      id: '/stock/$stockItemId'
      path: '/stock/$stockItemId'
      fullPath: '/stock/$stockItemId'
      preLoaderRoute: typeof StockStockItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials/$materialId': {
      id: '/raw-materials/$materialId'
      path: '/raw-materials/$materialId'
      fullPath: '/raw-materials/$materialId'
      preLoaderRoute: typeof RawMaterialsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verification': {
      id: '/auth/verification'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registration': {
      id: '/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/stocktake/': {
      id: '/stock/stocktake/'
      path: '/stock/stocktake'
      fullPath: '/stock/stocktake/'
      preLoaderRoute: typeof StockStocktakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/stocktake/$sessionId': {
      id: '/stock/stocktake/$sessionId'
      path: '/stock/stocktake/$sessionId'
      fullPath: '/stock/stocktake/$sessionId'
      preLoaderRoute: typeof StockStocktakeSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SettingsRoute: SettingsRoute,
  SimpleLoginRoute: SimpleLoginRoute,
  SimpleRegisterRoute: SimpleRegisterRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
  AuthVerificationRoute: AuthVerificationRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RawMaterialsMaterialIdRoute: RawMaterialsMaterialIdRoute,
  StockStockItemIdRoute: StockStockItemIdRoute,
  StockLabelsRoute: StockLabelsRoute,
  StockScanRoute: StockScanRoute,
  StockVerificationRoute: StockVerificationRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RawMaterialsIndexRoute: RawMaterialsIndexRoute,
  StockIndexRoute: StockIndexRoute,
  StockStocktakeSessionIdRoute: StockStocktakeSessionIdRoute,
  StockStocktakeIndexRoute: StockStocktakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
