"""add_stock_tracking_tables

Revision ID: 0c4f7c31295e
Revises: d4e5f6g7h8i9
Create Date: 2026-02-18 02:09:18.086707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4f7c31295e'
down_revision = 'd4e5f6g7h8i9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('red_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amber_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_supplier', sa.String(length=255), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_index('idx_raw_materials_code', 'raw_materials', ['material_code'], unique=False)
    op.create_index('idx_raw_materials_type', 'raw_materials', ['material_type'], unique=False)
    op.create_table('raw_material_movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('delivery_note', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_material_movements_date', 'raw_material_movements', ['created_at'], unique=False)
    op.create_index('idx_raw_material_movements_material', 'raw_material_movements', ['raw_material_id'], unique=False)
    op.create_table('stock_thresholds',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=True),
    sa.Column('red_threshold', sa.Integer(), nullable=False),
    sa.Column('amber_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_stock_threshold_product_colour', 'stock_thresholds', ['product_code', 'colour'], unique=True)
    op.create_table('stocktake_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_expected', sa.Integer(), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_discrepancies', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('barcode_id', sa.String(length=100), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('box_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('scanned_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_in_by', sa.UUID(), nullable=True),
    sa.Column('scanned_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_out_by', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('parent_stock_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['parent_stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['scanned_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scanned_out_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_id')
    )
    op.create_index('idx_stock_items_barcode', 'stock_items', ['barcode_id'], unique=False)
    op.create_index('idx_stock_items_order', 'stock_items', ['order_id'], unique=False)
    op.create_index('idx_stock_items_product', 'stock_items', ['product_code', 'colour'], unique=False)
    op.create_index('idx_stock_items_status', 'stock_items', ['status'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('stocktake_session_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['stocktake_session_id'], ['stocktake_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_movements_date', 'stock_movements', ['created_at'], unique=False)
    op.create_index('idx_stock_movements_item', 'stock_movements', ['stock_item_id'], unique=False)
    op.create_index('idx_stock_movements_order', 'stock_movements', ['order_id'], unique=False)
    op.create_index('idx_stock_movements_type', 'stock_movements', ['movement_type'], unique=False)
    op.create_table('stock_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_line_item_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=False),
    sa.Column('system_stock_quantity', sa.Integer(), nullable=False),
    sa.Column('verified_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_line_item_id'], ['order_line_items.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_verifications_line_item', 'stock_verifications', ['order_line_item_id'], unique=False)
    op.create_index('idx_stock_verifications_order', 'stock_verifications', ['order_id'], unique=False)
    op.create_index('idx_stock_verifications_status', 'stock_verifications', ['status'], unique=False)
    op.create_table('stocktake_scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('barcode_scanned', sa.String(length=100), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=True),
    sa.Column('scan_result', sa.String(length=20), nullable=False),
    sa.Column('scanned_by', sa.UUID(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['stocktake_sessions.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stocktake_scans_barcode', 'stocktake_scans', ['barcode_scanned'], unique=False)
    op.create_index('idx_stocktake_scans_session', 'stocktake_scans', ['session_id'], unique=False)
    op.add_column('products', sa.Column('is_stockable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_stockable')
    op.drop_index('idx_stocktake_scans_session', table_name='stocktake_scans')
    op.drop_index('idx_stocktake_scans_barcode', table_name='stocktake_scans')
    op.drop_table('stocktake_scans')
    op.drop_index('idx_stock_verifications_status', table_name='stock_verifications')
    op.drop_index('idx_stock_verifications_order', table_name='stock_verifications')
    op.drop_index('idx_stock_verifications_line_item', table_name='stock_verifications')
    op.drop_table('stock_verifications')
    op.drop_index('idx_stock_movements_type', table_name='stock_movements')
    op.drop_index('idx_stock_movements_order', table_name='stock_movements')
    op.drop_index('idx_stock_movements_item', table_name='stock_movements')
    op.drop_index('idx_stock_movements_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('idx_stock_items_status', table_name='stock_items')
    op.drop_index('idx_stock_items_product', table_name='stock_items')
    op.drop_index('idx_stock_items_order', table_name='stock_items')
    op.drop_index('idx_stock_items_barcode', table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_table('stocktake_sessions')
    op.drop_index('uq_stock_threshold_product_colour', table_name='stock_thresholds')
    op.drop_table('stock_thresholds')
    op.drop_index('idx_raw_material_movements_material', table_name='raw_material_movements')
    op.drop_index('idx_raw_material_movements_date', table_name='raw_material_movements')
    op.drop_table('raw_material_movements')
    op.drop_index('idx_raw_materials_type', table_name='raw_materials')
    op.drop_index('idx_raw_materials_code', table_name='raw_materials')
    op.drop_table('raw_materials')
    # ### end Alembic commands ###
