"""Add product catalog tables

Revision ID: 853ac57bb136
Revises: 16aefc3ebcc4
Create Date: 2026-02-07 02:34:58.658719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853ac57bb136'
down_revision = '16aefc3ebcc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index('idx_product_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_product_code', 'products', ['product_code'], unique=False)
    op.create_index('idx_product_customer', 'products', ['customer_name'], unique=False)
    op.create_table('manufacturing_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('mould_no', sa.String(length=50), nullable=True),
    sa.Column('cycle_time_seconds', sa.Integer(), nullable=True),
    sa.Column('shot_weight_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('num_cavities', sa.Integer(), nullable=True),
    sa.Column('product_weight_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_running_time_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('machine_min_requirements', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index('idx_mfg_product_code', 'manufacturing_specs', ['product_code'], unique=False)
    op.create_table('material_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=False),
    sa.Column('material_grade', sa.String(length=100), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('colour_no', sa.String(length=50), nullable=True),
    sa.Column('colour_supplier', sa.String(length=100), nullable=True),
    sa.Column('mb_add_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('additive', sa.String(length=100), nullable=True),
    sa.Column('additive_add_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('additive_supplier', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_material_product_code', 'material_specs', ['product_code'], unique=False)
    op.create_index('uq_material_product_colour', 'material_specs', ['product_code', 'colour'], unique=True)
    op.create_table('packaging_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('qty_per_bag', sa.Integer(), nullable=True),
    sa.Column('bag_size', sa.String(length=50), nullable=True),
    sa.Column('qty_per_carton', sa.Integer(), nullable=True),
    sa.Column('carton_size', sa.String(length=50), nullable=True),
    sa.Column('cartons_per_pallet', sa.Integer(), nullable=True),
    sa.Column('cartons_per_layer', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index('idx_packaging_product_code', 'packaging_specs', ['product_code'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_product_code', 'pricing', ['product_code'], unique=False)
    op.create_index('uq_pricing_product_colour', 'pricing', ['product_code', 'colour'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pricing_product_colour', table_name='pricing')
    op.drop_index('idx_pricing_product_code', table_name='pricing')
    op.drop_table('pricing')
    op.drop_index('idx_packaging_product_code', table_name='packaging_specs')
    op.drop_table('packaging_specs')
    op.drop_index('uq_material_product_colour', table_name='material_specs')
    op.drop_index('idx_material_product_code', table_name='material_specs')
    op.drop_table('material_specs')
    op.drop_index('idx_mfg_product_code', table_name='manufacturing_specs')
    op.drop_table('manufacturing_specs')
    op.drop_index('idx_product_customer', table_name='products')
    op.drop_index('idx_product_code', table_name='products')
    op.drop_index('idx_product_active', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
